# Graph Decoder Default Params
world_frame                             : map
visual_scale_ratio                      : 0.5
file_name                               : /home/fan-robot/graph_decoder_ws/data/graph.txt